version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: net.serenity-bdd:serenity-single-page-report
    versions:
    - 2.3.13
    - 2.4.1
    - 2.4.20
    - 2.4.3
    - 2.4.4
  - dependency-name: org.springdoc:springdoc-openapi-ui
    versions:
    - 1.5.3
    - 1.5.4
    - 1.5.5
    - 1.5.6
    - 1.5.7
  - dependency-name: uk.gov.hmcts.reform.probate:probate-commons
    versions:
    - 1.1.2.2
    - 1.1.2.3
  - dependency-name: net.serenity-bdd:serenity-gradle-plugin
    versions:
    - 2.3.12
    - 2.3.13
    - 2.4.2
  - dependency-name: com.gorylenko.gradle-git-properties
    versions:
    - 2.2.4
    - 2.3.0
  - dependency-name: uk.gov.hmcts.java
    versions:
    - 0.12.6
    - 0.12.7
  - dependency-name: au.com.dius.pact
    versions:
    - 4.2.0
    - 4.2.1
    - 4.2.2
    - 4.2.3
  - dependency-name: com.google.guava:guava
    versions:
    - 30.1.1-jre
  - dependency-name: org.apache.pdfbox:pdfbox
    versions:
    - 2.0.22
    - 2.0.23
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.pitest:pitest
    versions:
    - 1.6.3
    - 1.6.4
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: info.solidsoft.pitest
    versions:
    - 1.5.2
    - 1.6.0
  - dependency-name: com.github.ben-manes.versions
    versions:
    - 0.36.0
    - 0.38.0
  - dependency-name: org.junit.platform:junit-platform-commons
    versions:
    - 1.7.1
  - dependency-name: info.solidsoft.gradle.pitest:gradle-pitest-plugin
    versions:
    - 1.4.6
  - dependency-name: uk.gov.hmcts.reform:document-management-client
    versions:
    - 7.0.0
  - dependency-name: au.com.dius:pact-jvm-provider-spring_2.12
    versions:
    - 3.6.15
  - dependency-name: org.sonarqube
    versions:
    - 3.1.1
  - dependency-name: uk.gov.hmcts.reform:properties-volume-spring-boot-starter
    versions:
    - 0.1.0
  - dependency-name: org.owasp.dependencycheck
    versions:
    - 6.1.1
  - dependency-name: uk.gov.hmcts.reform:service-auth-provider-client
    versions:
    - 3.1.4
    - 4.0.0
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.0
    - 5.7.1
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.0
    - 5.7.1
  - dependency-name: io.spring.dependency-management
    versions:
    - 1.0.11.RELEASE
  - dependency-name: uk.gov.service.notify:notifications-java-client
    versions:
    - 3.17.0-RELEASE
  - dependency-name: javax.ws.rs:javax.ws.rs-api
    versions:
    - 2.1.1
