---
#  security:
#    basic:
#      enabled: false
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /
  endpoint:
    health:
      show-details: always
      enabled: true
  info:
    git:
      mode: full

spring:
  application:
    name: probate-business-service
  messages:
    basename: messages
    cache-seconds: -1
    encoding: UTF-8
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      wrap_root_value: false
    deserialization:
      unwrap_root_value: true
  info:
    git:
      location: classpath:uk/gov/hmcts/probate/services/business/git.properties
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
services:
  auth:
    provider:
      totp_secret: "AAAAAAAAAAAAAAAA"
      baseUrl: http://localhost:4502
      microservice: "probate_backend"
      tokenTimeToLiveInSeconds: '900'
  persistence:
    baseUrl: http://localhost:8282
    invitedata:
      url: ${services.persistence.baseUrl}/invitedata
    formdata:
      url: ${services.persistence.baseUrl}/formdata
  notify:
    apiKey: ${PROBATE_NOTIFY_KEY:dummykey}
    invitedata:
      templateId: "29e5c50d-1c86-449c-bb06-8cd465edfce6"
      bilingualTemplateId: "df526a14-8da2-4cd9-bb7a-cd757b08258"
      inviteLink: "http://localhost:3000/executors/invitation/"
    executorNotification:
      templateId: "193ff0e4-18b6-45bb-b0e3-cfd14f66151e"
      bilingualTemplateId: "3b8d6c77-2e24-46cf-aff5-113f35c22f2f"
      allSignedTemplateId: "3c7879db-6c8e-4622-b1a7-6773813deb62"
      allSignedBilingualTemplateId: "564c535c-9f11-4390-a889-0459ca59fa75"
    pin:
      templateId: "c0e11486-b8b3-4c22-a1ae-805a0ad2f641"
      bilingualTemplateId: "724a2e58-f0fd-421d-986d-ad5c4b5a47c2"
    documentNotification:
      templateId: "27c432a7-9d5a-4fd8-bea0-d7f678976a05"
      uploadIssueTemplateId: "80695a05-8dde-418d-b578-ee47fa24f900"
      bilingualTemplateId: "059235a6-f248-43ce-87d6-561352fbd89"
      bilingualUploadIssueTemplateId: "3e8d8469-98c6-4c0c-88d6-1b86580722f0"
  pdf:
    service:
      url: http://localhost:5500
      pdfApi: /api/v2/pdf-generator/html
      templatesDirectory: templates/pdf/

idam:
  s2s-auth:
    url: ${services.auth.provider.baseUrl}

  logging:
    level:
      org.springframework.web: ERROR
      au.com.dius.pact: DEBUG
    pattern:
      console: "%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n"
