---
  security:
    basic:
      enabled: false

  management:
    security:
      enabled: false

  server:
    port: 8080

  spring:
    application:
      name: probate-business-service
    messages:
      basename: messages
      cache-seconds: -1
      encoding: UTF-8

    jackson:
      serialization:
        wrap_root_value: false
      deserialization:
        unwrap_root_value: true

  services:
    persistence:
      baseUrl: http://localhost:8282
      invitedata:
        url: ${services.persistence.baseUrl}/invitedata
      formdata:
        url: ${services.persistence.baseUrl}/formdata
    notify:
      apiKey: "dummykey"
      invitedata:
        templateId: "dummykey"
        inviteLink: "http://localhost:3000/executors/invitation/"
      pin:
        templateId: "dummykey"

    pdf.service:
      url: http://localhost:5500
      pdfApi: /api/v2/pdf-generator/html
      templatesDirectory: templates/pdf/
      defaultDisplayFilename: dummy.pdf
      grantSignatureBase64: dummy_hash

  appinsights:
    intrumentationkey: false

  azure:
    app_insights_key: ${APPINSIGHTS_INSTRUMENTATIONKEY:false}
