---
#  security:
#    basic:
#      enabled: false
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,liveness
      base-path: /
  endpoint:
    health:
      show-details: always
      enabled: true
  info:
    git:
      mode: full

spring:
  application:
    name: probate-business-service
  config:
    import: "optional:configtree:/mnt/secrets/probate/"

  messages:
    basename: messages
    cache-seconds: -1
    encoding: UTF-8
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      wrap_root_value: false
    deserialization:
      unwrap_root_value: true
  info:
    git:
      location: classpath:uk/gov/hmcts/probate/services/business/git.properties
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
services:
  auth:
    provider:
      totp_secret: "AAAAAAAAAAAAAAAA"
      baseUrl: ${SERVICE_AUTH_PROVIDER_BASE_URL:http://localhost:4502}
      microservice: "probate_backend"
      tokenTimeToLiveInSeconds: '900'
  persistence:
    baseUrl: http://localhost:8282
    invitedata:
      url: ${services.persistence.baseUrl}/invitedata
    formdata:
      url: ${services.persistence.baseUrl}/formdata
  notify:
    apiKey: ${PROBATE_NOTIFY_KEY:dummykey}
    invitedata:
      templateId: "29e5c50d-1c86-449c-bb06-8cd465edfce6"
      bilingualTemplateId: "df526a14-8da2-4cd9-bb7a-cd757b082583"
      inviteLink: "http://localhost:3000/executors/invitation/"
    executorNotification:
      templateId: "8b9316de-1ca8-464e-bab6-5e14c7973af7"
      bilingualTemplateId: "37bc1d67-7f4a-4872-bfb1-d2f9eee34e47"
      allSignedTemplateId: "dce921d1-7510-48d7-a90c-4b6a3bea69e9"
      allSignedBilingualTemplateId: "aafa6219-e1ca-4a64-b62e-5cb3cbd5930b"
    pin:
      templateId: "c0e11486-b8b3-4c22-a1ae-805a0ad2f641"
      bilingualTemplateId: "724a2e58-f0fd-421d-986d-ad5c4b5a47c2"
    documentNotification:
      templateId: "5dca7815-0c52-4ee2-baca-2a52487b5cd9"
      uploadIssueTemplateId: "84a07e46-3302-41c8-911c-28c2fa509343"
      bilingualTemplateId: "bcb7479f-818e-46bb-a874-8ffa7bfb573b"
      bilingualUploadIssueTemplateId: "9611781d-b857-4f3e-a5a1-0e526444dfae"
  pdf:
    service:
      url: ${PDF_SERVICE_URL:http://localhost:5500}
      pdfApi: /api/v2/pdf-generator/html
      templatesDirectory: templates/pdf/

idam:
  s2s-auth:
    url: ${services.auth.provider.baseUrl}
