version: '2.1'

services:

  service-auth-provider-api:
    image: hmcts/service-auth-provider-app
    container_name: service-auth-provider-api
    environment:
    - SERVER_PORT=4502
    - JAVA_OPTS=-Xms8m -Xmx256m -Djava.security.egd=file:/dev/./urandom -XX:MaxMetaspaceSize=128m
    - JWT_KEY=wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==
    - MICROSERVICE_KEYS_EM_GW=AAAAAAAAAAAAAAAA
    - MICROSERVICE_KEYS_CCD_DATA=AAAAAAAAAAAAAAAA
    - MICROSERVICE_KEYS_CCD_DEFINITION=AAAAAAAAAAAAAAAA
    - MICROSERVICE_KEYS_CCD_GW=AAAAAAAAAAAAAAAA
    - MICROSERVICE_KEYS_CCD_PS=AAAAAAAAAAAAAAAA
    - TESTING_SUPPORT_ENABLED=true
    - MICROSERVICE_KEYS_PROBATE_BACKEND=AAAAAAAAAAAAAAAA
    ports:
    - 4502:4502






