applicationPort: 8080
image: hmctssandbox.azurecr.io/hmcts/probate-business-service
memoryRequests: '512Mi'
cpuRequests: '100m'
memoryLimits: '1024Mi'
cpuLimits: '2500m'
ingressHost: probate-frontend-aat.core-compute-aat.internal
readinessPath: '/health'
readinessDelay: 30
readinessTimeout: 3
readinessPeriod: 15
livenessPath: '/health'
livenessDelay: 30
livenessTimeout: 3
livenessPeriod: 15
livenessFailureThreshold: 3
