apiVersion: v2
name: probate-business-service
home: https://github.com/hmcts/probate-business-service
version: 0.1.13
description: HMCTS Probate Business Service
maintainers:
  - name: HMCTS Probate Team
    email: Probate@hmcts.net

dependencies:
  - name: java
    version: 4.0.11
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
