java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    probate:
      secrets:
        - name: business-services-notify-invitedata-templateId
          alias: services.notify.invitedata.templateId
        - name: business-services-notify-pin-templateId
          alias: services.notify.pin.templateId
        - name: s2s-probate-backend
          alias: services.auth.provider.totp_secret
