java:
  applicationPort: 8080
  aadIdentityName: probate
  ingressHost: probate-business-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  environment:
    REFORM_TEAM: probate
    REFORM_SERVICE_NAME: business-service
    SERVICES_AUTH_PROVIDER_BASEURL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    SERVICES_PDF_SERVICE_URL : http://cmc-pdf-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    SERVICES_PERSISTENCE_BASEURL: http://probate-persistence-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    DOCUMENT_MANAGEMENT_URL : http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    SERVICES_NOTIFY_INVITEDATA_INVITELINK : https://probate.{{ .Values.global.environment }}.platform.hmcts.net/executors/invitation/
  keyVaults:
    probate:
      secrets:
        - name: probate-notify-invite-apikey
          alias: services.notify.apiKey
        - name: business-services-notify-invitedata-templateId
          alias: services.notify.invitedata.templateId
        - name: business-services-notify-pin-templateId
          alias: services.notify.pin.templateId
        - name: s2s-probate-backend
          alias: services.auth.provider.totp_secret
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
  image: hmctspublic.azurecr.io/probate/probate-business-service:latest
