java:
  applicationPort: 8080
  environment:
    REFORM_TEAM: probate
    REFORM_SERVICE_NAME: business-service
    SERVICES_AUTH_PROVIDER_BASEURL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    SERVICES_PDF_SERVICE_URL : http://cmc-pdf-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    SERVICES_PERSISTENCE_BASEURL: http://probate-persistence-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    DOCUMENT_MANAGEMENT_URL : http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    SERVICES_NOTIFY_INVITEDATA_INVITELINK : http://probate-frontend-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/executors/invitation/
  keyVaults:
    "probate":
      resourceGroup: probate
      secrets:
        - probate-notify-invite-apikey
        - business-services-notify-invitedata-templateId
        - business-services-notify-pin-templateId
        - s2s-probate-backend
        - AppInsightsInstrumentationKey
  image: hmctspublic.azurecr.io/probate/probate-business-service:latest
