java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  aadIdentityName: probate
  environment:
    SERVICES_PERSISTENCE_BASEURL : http://probate-persistence-service-sandbox.service.core-compute-sandbox.internal
    SERVICES_NOTIFY_INVITEDATA_INVITELINK : http://probate-frontend-sandbox.service.core-compute-sandbox.internal/executors/invitation/
    SERVICES_PDF_SERVICE_URL : http://cmc-pdf-service-sandbox.service.core-compute-sandbox.internal
    SERVICES_AUTH_PROVIDER_BASEURL : http://rpe-service-auth-provider-sandbox.service.core-compute-sandbox.internal
    DOCUMENT_MANAGEMENT_URL : http://dm-store-sandbox.service.core-compute-sandbox.internal